### ISSUE TITLE
Validate Roadway Schema

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#32] opened 2019-05-24 16:50 UTC
* Use #31 to validate the input roadway
* Validator method

**Comment by josiekre** [comment] 2019-07-13 00:29
I think this is a duplicate of #40, right?

**Comment by e-lo** [comment] 2019-07-15 16:34
yes. i'll delete 40

**Comment by e-lo** [comment] 2019-07-17 04:04
Completed based on schema, but could add other validations in future.

**Comment by e-lo** [comment] 2019-08-01 15:32
This is done but will need to be updated as we evolve the network standard.

**Closed by e-lo** 2019-08-01 15:32 UTC
Labels: enhancement
